In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pwd

'C:\\Users\\emi\\Desktop\\UTN 2019\\CIENCIA DE DATOS\\tp'

In [3]:
#Pesaje Recibido en Puntos Verdes (2015-2016) en kilogramos.
#Importamos
filename = r'pesaje-recibido-en-puntos-verdes-2015-2016.csv'
pesajes = pd.read_csv(filename, delimiter=';', decimal=',')
print(f'Pesajes tiene: {np.shape(pesajes)[0]} filas y {np.shape(pesajes)[1]} columnas')

Pesajes tiene: 3080 filas y 15 columnas

### Transformamos los meses a valores numéricos

In [4]:
pesajes.loc[ pesajes['MES'] == "ENERO", 'MES'] = 1
pesajes.loc[ pesajes['MES'] == "FEBRERO", 'MES'] = 2
pesajes.loc[ pesajes['MES'] == "MARZO", 'MES'] = 3
pesajes.loc[ pesajes['MES'] == "ABRIL", 'MES'] = 4
pesajes.loc[ pesajes['MES'] == "MAYO", 'MES'] = 5
pesajes.loc[ pesajes['MES'] == "JUNIO", 'MES'] = 6
pesajes.loc[ pesajes['MES'] == "JULIO", 'MES'] = 7
pesajes.loc[ pesajes['MES'] == "AGOSTO", 'MES'] = 8
pesajes.loc[ pesajes['MES'] == "SEPTIEMBRE", 'MES'] = 9
pesajes.loc[ pesajes['MES'] == "OCTUBRE", 'MES'] = 10
pesajes.loc[ pesajes['MES'] == "NOVIEMBRE", 'MES'] = 11
pesajes.loc[ pesajes['MES'] == "DICIEMBRE", 'MES'] = 12

##   Criterios elegidos para limpiar el Dataframe

### Semana
Si una semana esta llena de 0s, "", " ", NaNs es considerada VACIA
### Mes
Si un mes tiene 3 o más semanas VACIAS -> Esta VACIO
Si un mes no esta cargado en el dataframe -> Esta VACIO
### Punto
Si un Punto tiene 4 o mas meses VACIOS en 2015 y 2016 -> Esta VACIO

### Transformo todos los lugares vacios en NaN

In [5]:
pesajes_con_nan = pesajes.replace(' ', np.nan).replace('', np.nan)
pesajes_con_nan

,PUNTO,COMUNA,ANIO,MES,SEMANA,VIDRIO,PAPEL_Y_CARTON,METAL,PLASTICO_PET,TELGOPOR,PLASTICOS_TODOS_LOS_DEMAS,TETRA_BRICK,PEQUENIOS_ELECTRODOMESTICOS,APARATOS_ELECTRONICOS_EN_DESUSO,AVUS
0,ESTACION VILLA SOLDATI,COMUNA 8,2015,4,1,"31,2","20,7","0,27",NaN,0,"13,41",0,NaN,NaN,NaN
1,ESTACION VILLA SOLDATI,COMUNA 8,2015,4,2,"2,231","44,878",0,NaN,0,"37,886","0,54",NaN,NaN,NaN
2,ESTACION VILLA SOLDATI,COMUNA 8,2015,4,3,"38,042","27,763","1,067",NaN,0,"17,57",0,NaN,NaN,NaN
3,ESTACION VILLA SOLDATI,COMUNA 8,2015,4,4,"28,42","37,64","1,48",NaN,0,"12,02",0,NaN,NaN,NaN
4,ESTACION VILLA SOLDATI,COMUNA 8,2015,4,5,"12,33","21,51",0,NaN,0,"4,36",0,NaN,NaN,NaN
5,ESTACION VILLA SOLDATI,COMUNA 8,2015,8,1,"12,785","22,496",0,0,0,"5,418",0,NaN,NaN,NaN
6,ESTACION VILLA SOLDATI,COMUNA 8,2015,8,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ESTACION VILLA SOLDATI,COMUNA 8,2015,8,3,"9,456","13,659",0,0,0,"3,741",0,NaN,NaN,NaN
8,ESTACION VILLA SOLDATI,COMUNA 8,2015,8,4,"9,451","16,871","1,496",0,0,"9,743",0,NaN,NaN,NaN
9,ESTACION VILLA SOLDATI,COMUNA 8,2015,8,5,"11,745","19,421",0,0,0,"5,741","0,421",NaN,NaN,NaN
10,ESTACION VILLA SOLDATI,COMUNA 8,2015,12,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,ESTACION VILLA SOLDATI,COMUNA 8,2015,12,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,ESTACION VILLA SOLDATI,COMUNA 8,2015,12,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,ESTACION VILLA SOLDATI,COMUNA 8,2015,12,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,ESTACION VILLA SOLDATI,COMUNA 8,2015,12,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,ESTACION VILLA SOLDATI,COMUNA 8,2015,1,1,"50,19","21,12","0,99",NaN,0,"10,28",NaN,NaN,NaN,NaN
16,ESTACION VILLA SOLDATI,COMUNA 8,2015,1,2,"75,58","28,33","0,72",NaN,"3,74","19,46",NaN,NaN,NaN,NaN
17,ESTACION VILLA SOLDATI,COMUNA 8,2015,1,3,"27,11","21,35","3,73",NaN,"0,57","29,13",NaN,NaN,NaN,NaN
18,ESTACION VILLA SOLDATI,COMUNA 8,2015,1,4,"33,32","15,98",0,NaN,0,"15,29",NaN,NaN,NaN,NaN
19,ESTACION VILLA SOLDATI,COMUNA 8,2015,1,5,"18,14","11,53","1,32",NaN,0,"10,11",NaN,NaN,NaN,NaN
20,ESTACION VILLA SOLDATI,COMUNA 8,2015,2,1,"12,63","16,79",0,NaN,0,"9,22",NaN,NaN,NaN,NaN
21,ESTACION VILLA SOLDATI,COMUNA 8,2015,2,2,"93,82","44,92","3,38",NaN,"3,77","27,75",NaN,NaN,NaN,NaN
22,ESTACION VILLA SOLDATI,COMUNA 8,2015,2,3,"89,59","24,12","2,77",NaN,"1,54","15,82",NaN,NaN,NaN,NaN
23,ESTACION VILLA SOLDATI,COMUNA 8,2015,2,4,"39,61","9,74",0,NaN,0,"10,73",NaN,NaN,NaN,NaN
24,ESTACION VILLA SOLDATI,COMUNA 8,2015,7,1,"10,758","6,12",0,0,0,16,0,NaN,NaN,NaN
25,ESTACION VILLA SOLDATI,COMUNA 8,2015,7,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,ESTACION VILLA SOLDATI,COMUNA 8,2015,7,3,"18,56","29,459",0,0,0,16,"0,789",NaN,NaN,NaN
27,ESTACION VILLA SOLDATI,COMUNA 8,2015,7,4,"19,46","22,43","1,32",0,0,"19,46",0,NaN,NaN,NaN
28,ESTACION VILLA SOLDATI,COMUNA 8,2015,6,1,"42,42","23,415",0,0,0,"19,458",0,NaN,NaN,NaN
29,ESTACION VILLA SOLDATI,COMUNA 8,2015,6,2,"29,458","38,451","0,87",0,0,"8,746",0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3050,PUERTO MADERO,COMUNA 1,2016,9,2,"10,187","120,3",0,NaN,0,"25,053",0,NaN,NaN,NaN
3051,PUERTO MADERO,COMUNA 1,2016,9,3,"9,389","57,334","3,5",NaN,0,"11,325",0,NaN,NaN,NaN
3052,PUERTO MADERO,COMUNA 1,2016,9,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3053,PUERTO MADERO,COMUNA 1,2016,9,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3054,PARQUE CENTENARIO,COMUNA 6,2016,11,1,"387,057","778,211","25,3","101,194","7,891","251,071","18,745","31,156","130,73","17,6"
3055,PARQUE CENTENARIO,COMUNA 6,2016,11,2,"298,85","752,227","17,514","76,949","4,735","167,547","13,529","23,306","56,481","26,4"
3056,PARQUE CENTENARIO,COMUNA 6,2016,11,3,"165,908","335,4","14,929","68,223","3,893","82,49","21,027","19,186","38,624",22
3057,PARQUE CENTENARIO,COMUNA 6,2016,11,4,"264,742","447,998","20,285","37,606","18,342","136,361","14,159","42,552","70,24",44
3058,PLAZA ARENALES,COMUNA 11,2016,11,1,"653,364","1189,367","30,616","215,471","27,03","306,589","27,03","27,74","54,75","35,99"
3059,PLAZA ARENALES,COMUNA 11,2016,11,2,"871,141","1375,584","32,52","259,423","9,623","290,974","38,186","167,674","182,976","32,56"
3060,PLAZA ARENALES,COMUNA 11,2016,11,3,"938,9","1306,463","63,5","271,67","10,374","338,924","36,136","122,698","198,049","8,8"
3061,PLAZA ARENALES,COMUNA 11,2016,11,4,"712,82","953,545","32,6","235,066","9,141","302,269","16,507","81,869","217,141","35,2"
3062,PLAZA GUEMES,COMUNA 14,2016,11,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"6,16"
3063,PLAZA GUEMES,COMUNA 14,2016,11,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"13,2"
3064,PLAZA GUEMES,COMUNA 14,2016,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44
3065,PLAZA GUEMES,COMUNA 14,2016,11,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"17,6"
3066,PLAZA SUDAMERICANA,COMUNA 8,2016,11,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,76"
3067,PLAZA SUDAMERICANA,COMUNA 8,2016,11,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,056"
3068,PLAZA SUDAMERICANA,COMUNA 8,2016,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"8,8"
3069,PLAZA SUDAMERICANA,COMUNA 8,2016,11,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"4,4"
3070,PARQUE CENTENARIO,COMUNA 6,2016,12,1,"329,984","610,387","22,215","76,343","4,599","139,759","8,603","28,113","86,545","26,576"
3071,PARQUE CENTENARIO,COMUNA 6,2016,12,2,"383,194","571,736","17,367","89,647","6,82","162,844","21,534","94,586","134,125","130,5"
3072,PARQUE CENTENARIO,COMUNA 6,2016,12,3,"242,445","601,388","12,505","98,552","5,241","144,428","27,235","44,569","97,609","35,2"
3073,PARQUE CENTENARIO,COMUNA 6,2016,12,4,"335,436","619,398","19,187","59,804","2,996","123,124","11,479","4,994","53,728","13,64"
3074,PARQUE CENTENARIO,COMUNA 6,2016,12,5,"470,249","1154,007","31,622","164,664","5,512","146,346","26,21","94,767","134,145","8,89"
3075,PLAZA ARENALES,COMUNA 11,2016,12,1,"948,639","1291,304","57,743","291,558","8,028","288,202","24,406","102,955","294,847","26,84"
3076,PLAZA ARENALES,COMUNA 11,2016,12,2,"977,875","1614,608","45,038","275,053","8,568","357,738","17,727","85,162","273,249","132,528"
3077,PLAZA ARENALES,COMUNA 11,2016,12,3,"799,564","1382,172","35,12","249,659","6,48","221,876","38,498","94,379","224,842","12,32"
3078,PLAZA ARENALES,COMUNA 11,2016,12,4,"786,412","1184,086","24,871","206,937","20,648","195,612","20,893","45,351","70,141","27,104"
3079,PLAZA ARENALES,COMUNA 11,2016,12,5,"858,121","1087,819","101,145","287,571","14,571","282,258","44,207","69,095","55,239",11

In [6]:
np.shape(pesajes_con_nan)

(3080, 15)

###  Cuantos puntos y comunas distintas hay?

Mapa de comunas en este [link](https://www.google.com/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2F4%2F4b%2FBuenos_Aires_Comunas.svg%2F1200px-Buenos_Aires_Comunas.svg.png&imgrefurl=https%3A%2F%2Fes.wikipedia.org%2Fwiki%2FComunas_de_la_ciudad_de_Buenos_Aires&docid=Ezlwe5ezJGTRlM&tbnid=FSUavRrKMRElQM%3A&vet=10ahUKEwiXpNLmjs7kAhW2HbkGHTRqD2sQMwhRKAAwAA..i&w=1200&h=1222&bih=878&biw=958&q=comunas%20caba&ved=0ahUKEwiXpNLmjs7kAhW2HbkGHTRqD2sQMwhRKAAwAA&iact=mrc&uact=8)

In [7]:
comunas_distintas = np.unique(pesajes.COMUNA)
print(f'Hay {len(comunas_distintas)} comunas distintas')

puntos_distintos = np.unique(pesajes.PUNTO)
print(f'Hay {len(puntos_distintos)} puntos distintos distribuidos entre las comunas')
#pesajes['VIDRIO'][0]

Hay 15 comunas distintas
Hay 32 puntos distintos distribuidos entre las comunas

In [8]:
pesajes_con_nan.isnull().sum()

PUNTO                                 0
COMUNA                                0
ANIO                                  0
MES                                   0
SEMANA                                0
VIDRIO                              370
PAPEL_Y_CARTON                      371
METAL                               371
PLASTICO_PET                       1284
TELGOPOR                            371
PLASTICOS_TODOS_LOS_DEMAS           369
TETRA_BRICK                         738
PEQUENIOS_ELECTRODOMESTICOS        2872
APARATOS_ELECTRONICOS_EN_DESUSO    2872
AVUS                               2993
dtype: int64

La cantidad de Nan en PEQUENIOS_ELECTRODOMESTICOS, APARATOS_ELECTRONICOS_EN_DESUSO y AVUS tienen su sentido, de los 32 puntos verdes, 30 son puntos verdes comunes que juntan vidrio, papel, carton, metal, plastico, tetra brick y plastico, y hay 2 puntos verdes que ademas de juntar lo anteriormente mencionado, juntan PEQUENIOS_ELECTRODOMESTICOS, APARATOS_ELECTRONICOS_EN_DESUSO y AVUS. Para poder hacer una mejor comparacion entre los puntos verdes, vamos a considerar los 32 iguales, descartando estas 3 columnas.

In [9]:
pesajes_con_nan = pesajes_con_nan.iloc[:,0:12]
pesajes_con_nan

,PUNTO,COMUNA,ANIO,MES,SEMANA,VIDRIO,PAPEL_Y_CARTON,METAL,PLASTICO_PET,TELGOPOR,PLASTICOS_TODOS_LOS_DEMAS,TETRA_BRICK
0,ESTACION VILLA SOLDATI,COMUNA 8,2015,4,1,"31,2","20,7","0,27",NaN,0,"13,41",0
1,ESTACION VILLA SOLDATI,COMUNA 8,2015,4,2,"2,231","44,878",0,NaN,0,"37,886","0,54"
2,ESTACION VILLA SOLDATI,COMUNA 8,2015,4,3,"38,042","27,763","1,067",NaN,0,"17,57",0
3,ESTACION VILLA SOLDATI,COMUNA 8,2015,4,4,"28,42","37,64","1,48",NaN,0,"12,02",0
4,ESTACION VILLA SOLDATI,COMUNA 8,2015,4,5,"12,33","21,51",0,NaN,0,"4,36",0
5,ESTACION VILLA SOLDATI,COMUNA 8,2015,8,1,"12,785","22,496",0,0,0,"5,418",0
6,ESTACION VILLA SOLDATI,COMUNA 8,2015,8,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ESTACION VILLA SOLDATI,COMUNA 8,2015,8,3,"9,456","13,659",0,0,0,"3,741",0
8,ESTACION VILLA SOLDATI,COMUNA 8,2015,8,4,"9,451","16,871","1,496",0,0,"9,743",0
9,ESTACION VILLA SOLDATI,COMUNA 8,2015,8,5,"11,745","19,421",0,0,0,"5,741","0,421"
10,ESTACION VILLA SOLDATI,COMUNA 8,2015,12,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,ESTACION VILLA SOLDATI,COMUNA 8,2015,12,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,ESTACION VILLA SOLDATI,COMUNA 8,2015,12,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,ESTACION VILLA SOLDATI,COMUNA 8,2015,12,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,ESTACION VILLA SOLDATI,COMUNA 8,2015,12,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,ESTACION VILLA SOLDATI,COMUNA 8,2015,1,1,"50,19","21,12","0,99",NaN,0,"10,28",NaN
16,ESTACION VILLA SOLDATI,COMUNA 8,2015,1,2,"75,58","28,33","0,72",NaN,"3,74","19,46",NaN
17,ESTACION VILLA SOLDATI,COMUNA 8,2015,1,3,"27,11","21,35","3,73",NaN,"0,57","29,13",NaN
18,ESTACION VILLA SOLDATI,COMUNA 8,2015,1,4,"33,32","15,98",0,NaN,0,"15,29",NaN
19,ESTACION VILLA SOLDATI,COMUNA 8,2015,1,5,"18,14","11,53","1,32",NaN,0,"10,11",NaN
20,ESTACION VILLA SOLDATI,COMUNA 8,2015,2,1,"12,63","16,79",0,NaN,0,"9,22",NaN
21,ESTACION VILLA SOLDATI,COMUNA 8,2015,2,2,"93,82","44,92","3,38",NaN,"3,77","27,75",NaN
22,ESTACION VILLA SOLDATI,COMUNA 8,2015,2,3,"89,59","24,12","2,77",NaN,"1,54","15,82",NaN
23,ESTACION VILLA SOLDATI,COMUNA 8,2015,2,4,"39,61","9,74",0,NaN,0,"10,73",NaN
24,ESTACION VILLA SOLDATI,COMUNA 8,2015,7,1,"10,758","6,12",0,0,0,16,0
25,ESTACION VILLA SOLDATI,COMUNA 8,2015,7,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,ESTACION VILLA SOLDATI,COMUNA 8,2015,7,3,"18,56","29,459",0,0,0,16,"0,789"
27,ESTACION VILLA SOLDATI,COMUNA 8,2015,7,4,"19,46","22,43","1,32",0,0,"19,46",0
28,ESTACION VILLA SOLDATI,COMUNA 8,2015,6,1,"42,42","23,415",0,0,0,"19,458",0
29,ESTACION VILLA SOLDATI,COMUNA 8,2015,6,2,"29,458","38,451","0,87",0,0,"8,746",0
...,...,...,...,...,...,...,...,...,...,...,...,...
3050,PUERTO MADERO,COMUNA 1,2016,9,2,"10,187","120,3",0,NaN,0,"25,053",0
3051,PUERTO MADERO,COMUNA 1,2016,9,3,"9,389","57,334","3,5",NaN,0,"11,325",0
3052,PUERTO MADERO,COMUNA 1,2016,9,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3053,PUERTO MADERO,COMUNA 1,2016,9,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3054,PARQUE CENTENARIO,COMUNA 6,2016,11,1,"387,057","778,211","25,3","101,194","7,891","251,071","18,745"
3055,PARQUE CENTENARIO,COMUNA 6,2016,11,2,"298,85","752,227","17,514","76,949","4,735","167,547","13,529"
3056,PARQUE CENTENARIO,COMUNA 6,2016,11,3,"165,908","335,4","14,929","68,223","3,893","82,49","21,027"
3057,PARQUE CENTENARIO,COMUNA 6,2016,11,4,"264,742","447,998","20,285","37,606","18,342","136,361","14,159"
3058,PLAZA ARENALES,COMUNA 11,2016,11,1,"653,364","1189,367","30,616","215,471","27,03","306,589","27,03"
3059,PLAZA ARENALES,COMUNA 11,2016,11,2,"871,141","1375,584","32,52","259,423","9,623","290,974","38,186"
3060,PLAZA ARENALES,COMUNA 11,2016,11,3,"938,9","1306,463","63,5","271,67","10,374","338,924","36,136"
3061,PLAZA ARENALES,COMUNA 11,2016,11,4,"712,82","953,545","32,6","235,066","9,141","302,269","16,507"
3062,PLAZA GUEMES,COMUNA 14,2016,11,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3063,PLAZA GUEMES,COMUNA 14,2016,11,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3064,PLAZA GUEMES,COMUNA 14,2016,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3065,PLAZA GUEMES,COMUNA 14,2016,11,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3066,PLAZA SUDAMERICANA,COMUNA 8,2016,11,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3067,PLAZA SUDAMERICANA,COMUNA 8,2016,11,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3068,PLAZA SUDAMERICANA,COMUNA 8,2016,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3069,PLAZA SUDAMERICANA,COMUNA 8,2016,11,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3070,PARQUE CENTENARIO,COMUNA 6,2016,12,1,"329,984","610,387","22,215","76,343","4,599","139,759","8,603"
3071,PARQUE CENTENARIO,COMUNA 6,2016,12,2,"383,194","571,736","17,367","89,647","6,82","162,844","21,534"
3072,PARQUE CENTENARIO,COMUNA 6,2016,12,3,"242,445","601,388","12,505","98,552","5,241","144,428","27,235"
3073,PARQUE CENTENARIO,COMUNA 6,2016,12,4,"335,436","619,398","19,187","59,804","2,996","123,124","11,479"
3074,PARQUE CENTENARIO,COMUNA 6,2016,12,5,"470,249","1154,007","31,622","164,664","5,512","146,346","26,21"
3075,PLAZA ARENALES,COMUNA 11,2016,12,1,"948,639","1291,304","57,743","291,558","8,028","288,202","24,406"
3076,PLAZA ARENALES,COMUNA 11,2016,12,2,"977,875","1614,608","45,038","275,053","8,568","357,738","17,727"
3077,PLAZA ARENALES,COMUNA 11,2016,12,3,"799,564","1382,172","35,12","249,659","6,48","221,876","38,498"
3078,PLAZA ARENALES,COMUNA 11,2016,12,4,"786,412","1184,086","24,871","206,937","20,648","195,612","20,893"
3079,PLAZA ARENALES,COMUNA 11,2016,12,5,"858,121","1087,819","101,145","287,571","14,571","282,258","44,207"

In [10]:
#Separo 2015 y 2016
pesajes_2015 = pesajes_con_nan.loc[pesajes['ANIO'] == 2015]
np.shape(pesajes_2015)

(1731, 12)

In [11]:
pesajes_2016 = pesajes_con_nan.loc[pesajes['ANIO'] == 2016]
np.shape(pesajes_2016)

(1349, 12)

# Analisis de cantidad de datos en mes

Antes de analizar las comunas, analizaremos si todos los meses estan con datos, para saber si nuestro dataframe llega de enero 2015 a diciembre 2016, o si el GCBA no recaudo data en algun periodo en particular.

Empezamos analizando 2015

In [12]:
# Primero analizo si todos los meses tienen datos
# Creo un dataframe que tenga mes, anio y la cantidad de datos que contiene, para saber si hay meses faltantes
meses_2015 = pd.DataFrame({"ANIO":[],"MES":[],"N_DATOS":[]})
meses_2015
mesAnterior = 0 #lo arranco en un mes inexistente
semanas_del_Mes = 0

for indice in range(0, len(pesajes_2015)):
    mesActual = pesajes_2015.iloc[indice].MES
    if (mesAnterior == mesActual):
        semanas_del_Mes += 1
    else:
        mesAnterior = mesActual
        meses_2015 = meses_2015.append(
                {"N_DATOS": semanas_del_Mes,
                 "ANIO": 2015,
                 "MES": mesActual}, ignore_index=True)
        semanas_del_Mes = 1 #Reseteo el contador

meses_2015_tabla = meses_2015.groupby(["MES", "ANIO"])["N_DATOS"].count().sort_values(ascending=False)
meses_2015_tabla

MES   ANIO
12.0  2015.0    32
11.0  2015.0    32
10.0  2015.0    32
9.0   2015.0    32
8.0   2015.0    32
7.0   2015.0    32
6.0   2015.0    32
5.0   2015.0    32
4.0   2015.0    32
3.0   2015.0    32
2.0   2015.0    32
1.0   2015.0    32
Name: N_DATOS, dtype: int64

En 2015, las 32 comunas tienen al menos algun dato cargado en todos los meses, por lo que lo podemos considerar que en todo 2015 GCBA recgio datos de todos los puntos verdes.

Ahora analizamos 2016.

In [13]:
# Primero analizo si todos los meses tienen datos
# Creo un dataframe que tenga mes, anio y la cantidad de datos que contiene, para saber si hay meses faltantes
meses_2016 = pd.DataFrame({"ANIO":[],"MES":[],"N_DATOS":[]})
meses_2016
mesAnterior = 0 #lo arranco en un mes inexistente
semanas_del_Mes = 0

for indice in range(0, len(pesajes_2016)):
    mesActual = pesajes_2016.iloc[indice].MES
    if (mesAnterior == mesActual):
        semanas_del_Mes += 1
    else:
        mesAnterior = mesActual
        meses_2016 = meses_2016.append(
                {"N_DATOS": semanas_del_Mes,
                 "ANIO": 2016,
                 "MES": mesActual}, ignore_index=True)
        semanas_del_Mes = 1 #Reseteo el contador

meses_2016_tabla = meses_2016.groupby(["MES", "ANIO"])["N_DATOS"].count().sort_values(ascending=False)
meses_2016_tabla

MES   ANIO
9.0   2016.0    32
8.0   2016.0    32
7.0   2016.0    32
5.0   2016.0    32
4.0   2016.0    32
3.0   2016.0    32
2.0   2016.0    32
1.0   2016.0    32
6.0   2016.0    30
10.0  2016.0     4
12.0  2016.0     2
11.0  2016.0     2
Name: N_DATOS, dtype: int64

En el mes 10-2016, solo 4 puntos verdes de 32 tienen datos, y tanto 11-2016 como 12-2016, solo dos puntos verdes de 32 tienen datos. Ante este panorama, vamos a descartar los ultimos 3 meses de 2016, y vamos a hacer nuestro analisis de enero 2015 a septiembre 2016.

In [14]:
pesajes_sin12 = pesajes_con_nan.loc[~((pesajes_con_nan['ANIO'] == 2016) & (pesajes_con_nan['MES'] == 12))]
pesajes_sin11 = pesajes_sin12.loc[~((pesajes_sin12['ANIO'] == 2016) & (pesajes_sin12['MES'] == 11))]
pesajes_con_nan_sin_10_11_12 = pesajes_sin11.loc[~((pesajes_sin11['ANIO'] == 2016) & (pesajes_sin11['MES'] == 10))]
pesajes_con_nan = pesajes_con_nan_sin_10_11_12

In [15]:
np.shape(pesajes_con_nan)

(3029, 12)

In [16]:
pesajes_2016sin12 = pesajes_2016.loc[~((pesajes_2016['ANIO'] == 2016) & (pesajes_2016['MES'] == 12))]
pesajes_2016sin11 = pesajes_2016sin12.loc[~((pesajes_2016sin12['ANIO'] == 2016) & (pesajes_2016sin12['MES'] == 11))]
pesajes_2016_sin_10_11_12 = pesajes_2016sin11.loc[~((pesajes_2016sin11['ANIO'] == 2016) & (pesajes_2016sin11['MES'] == 10))]
pesajes_2016 = pesajes_2016_sin_10_11_12

In [17]:
np.shape(pesajes_2016)

(1298, 12)



### Cuento los meses que aparecen tienen 3 o mas semanas vacias, es decir con su fila rellena de  0, "", " " o NaN.

In [18]:
#Primero filtro las que tienen meses con todas las filas llenas de cero (si tienen esas 3 vacias, el resto tambien)
filtro1 = pesajes_2015['VIDRIO'].isin([0,np.nan," "])
filtro2 = pesajes_2015['PAPEL_Y_CARTON'].isin([0,np.nan," "])
filtro3 = pesajes_2015['METAL'].isin([0,np.nan," "])
sin_vacio = (filtro1 & filtro2 & filtro3)
pesajes_2015_semanas_vacias = pesajes_2015[sin_vacio].drop_duplicates().sort_values(by=['PUNTO', 'MES','SEMANA']).copy().reset_index(drop=True)


filtro1 = pesajes_2016['VIDRIO'].isin([0,np.nan," "])
filtro2 = pesajes_2016['PAPEL_Y_CARTON'].isin([0,np.nan," "])
filtro3 = pesajes_2016['METAL'].isin([0,np.nan," "])
sin_vacio = (filtro1 & filtro2 & filtro3)
pesajes_2016_semanas_vacias = pesajes_2016[sin_vacio].drop_duplicates().sort_values(by=['PUNTO', 'MES','SEMANA']).copy().reset_index(drop=True)

In [19]:
# Leo todas las semanas faltantes, si llego a 3 en el mismo mes lo guardo en el
# siguiente dataframe para luego borrarlos todos juntos
meses_Vacios_2015 = pd.DataFrame({"PUNTO":[],"ANIO":[],"MES":[]})

mesAnterior = 0 #lo arranco en un mes inexistente

for indice in range(0, len(pesajes_2015_semanas_vacias)):
    mesActual = pesajes_2015_semanas_vacias.iloc[indice].MES
    if (mesAnterior == mesActual):
        semanas_vacias_del_Mes += 1
        if(semanas_vacias_del_Mes != 3):
            continue
        else:
            meses_Vacios_2015 = meses_Vacios_2015.append(
                {"PUNTO": pesajes_2015_semanas_vacias.iloc[indice].PUNTO,
                 "ANIO": 2015,
                 "MES": mesActual}, ignore_index=True)
    else:
        mesAnterior = mesActual
        semanas_vacias_del_Mes = 1 #Reseteo el contador

meses_Vacios_2015_tabla = meses_Vacios_2015.groupby(["PUNTO", "ANIO"])["MES"].count().sort_values(ascending=False)
meses_Vacios_2015_tabla = pd.concat([meses_Vacios_2015_tabla], axis=1, keys=['Meses vacios por tener al menos 3 semanas vacias'])
meses_Vacios_2015_tabla

                               Meses vacios por tener al menos 3 semanas vacias
PUNTO                  ANIO
PLAZA 25 DE AGOSTO     2015.0                                                11
PLAZA VELAZCO IBARRA   2015.0                                                 4
ESTACION VILLA SOLDATI 2015.0                                                 4

In [20]:
# Leo todas las semanas faltantes, si llego a 3 en el mismo mes lo guardo en el
# siguiente dataframe para luego borrarlos todos juntos
meses_Vacios_2016 = pd.DataFrame({"PUNTO":[],"ANIO":[],"MES":[]})

mesAnterior = 0 #lo arranco en un mes inexistente

for indice in range(0, len(pesajes_2016_semanas_vacias)):
    mesActual = pesajes_2016_semanas_vacias.iloc[indice].MES
    if (mesAnterior == mesActual):
        semanas_vacias_del_Mes += 1
        if(semanas_vacias_del_Mes != 3):
            continue
        else:
            meses_Vacios_2016 = meses_Vacios_2016.append(
                {"PUNTO": pesajes_2016_semanas_vacias.iloc[indice].PUNTO,
                 "ANIO": 2016,
                 "MES": mesActual}, ignore_index=True)
    else:
        mesAnterior = mesActual
        semanas_vacias_del_Mes = 1 #Reseteo el contador

In [21]:
# Leo todas las semanas faltantes, si llego a 3 en el mismo mes lo guardo en el
# siguiente dataframe para luego borrarlos todos juntos
meses_Vacios_2016 = pd.DataFrame({"PUNTO":[],"ANIO":[],"MES":[]})

mesAnterior = 0 #lo arranco en un mes inexistente

for indice in range(0, len(pesajes_2016_semanas_vacias)):
    mesActual = pesajes_2016_semanas_vacias.iloc[indice].MES
    if (mesAnterior == mesActual):
        semanas_vacias_del_Mes += 1
        if(semanas_vacias_del_Mes != 3):
            continue
        else:
            meses_Vacios_2016 = meses_Vacios_2016.append(
                {"PUNTO": pesajes_2016_semanas_vacias.iloc[indice].PUNTO,
                 "ANIO": 2016,
                 "MES": mesActual}, ignore_index=True)
    else:
        mesAnterior = mesActual
        semanas_vacias_del_Mes = 1 #Reseteo el contador

meses_Vacios_2016_tabla = meses_Vacios_2016.groupby(["PUNTO", "ANIO"])["MES"].count().sort_values(ascending=False)
meses_Vacios_2016_tabla = pd.concat([meses_Vacios_2016_tabla], axis=1, keys=['Meses vacios por tener al menos 3 semanas vacias'])
meses_Vacios_2016_tabla

                               Meses vacios por tener al menos 3 semanas vacias
PUNTO                  ANIO
PLAZA 25 DE AGOSTO     2016.0                                                 8
ESTACION VILLA SOLDATI 2016.0                                                 8
PLAZA M BELGRANO       2016.0                                                 2
PLAZA SAN MARTIN       2016.0                                                 1

2015 no tiene meses faltantes no cargados.

En el Año 2016 hay muchos meses que no estan cargados. Vamos a contarlos incluyendo los que estan vacíos por cada uno de los Puntos.

Luego eliminamos los barrios que tengan 4 o mas meses vacios entre los 2 años.

In [23]:
## Creo un df de los meses que tengo cargados de cada año, ordenados
meses_cargados_2015 = pesajes_2015.iloc[:,[0,3]].drop_duplicates().sort_values(by=['PUNTO', 'MES'])
meses_cargados_2015 = meses_cargados_2015.copy().reset_index(drop=True)
print(f'\n2015 tiene todos los meses cargados, 32(puntos)x12(meses) = {np.shape(meses_cargados_2015)[0]}\n')

meses_cargados_2016 = pesajes_2016.iloc[:,[0,3]].drop_duplicates().sort_values(by=['PUNTO', 'MES'])
meses_cargados_2016 = meses_cargados_2016.copy().reset_index(drop=True)
print(f'2016 le faltan meses en algunos Puntos, tiene {np.shape(meses_cargados_2016)[0]} meses cargados')
print(f'\nLos numeros de meses que faltan por cada Punto esta guardada en\nla variable meses_faltantes')
    
## Los comparo y obtengo un df de todos los meses faltantes con PUNTO y MES
meses_faltantes = pd.merge(meses_cargados_2015, meses_cargados_2016,
                           how='outer', indicator=True).query('_merge == "left_only"')

meses_faltantes_por_barrio = meses_faltantes.groupby(["PUNTO"])["MES"].count().sort_values(ascending=False)
    
## Agrego los 2 puntos sin falta de meses para que quede completa la lista
puntos_sin_meses_faltantes = list(filter(lambda x: x not in meses_faltantes_por_barrio.index, puntos_distintos))

Tabla_Faltantes = pd.concat([meses_faltantes_por_barrio], axis=1, keys=['Meses faltantes por barrio en 2016'])

meses_faltantes = meses_faltantes.iloc[:,0:2]

#Tabla_Faltantes

print("\nTabla_Faltantes tiene la cantidad de meses faltantes por barrio\nen 2016")

2015 tiene todos los meses cargados, 32(puntos)x12(meses) = 384

2016 le faltan meses en algunos Puntos, tiene 286 meses cargados

Los numeros de meses que faltan por cada Punto esta guardada en
la variable meses_faltantes

Tabla_Faltantes tiene la cantidad de meses faltantes por barrio
en 2016

In [25]:
Tabla_de_Vacios_Completa = meses_faltantes.groupby(["PUNTO"])["MES"].count().sort_values(ascending=False)

## Agrego los 2 puntos sin falta de meses para que quede completa la lista
puntos_sin_meses_faltantes_2 = list(filter(lambda x: x not in Tabla_de_Vacios_Completa.index, puntos_distintos))
Tabla_de_Vacios_Completa = Tabla_de_Vacios_Completa.to_frame().rename(columns = {"MES":"Faltantes_2016"})

In [26]:
Agregar_a_tabla_vacias = pesajes_2016_semanas_vacias.groupby(["PUNTO", "MES"]).filter(lambda x: x["SEMANA"].count() >= 3)
Agregar_a_tabla_vacias_filtrada_2016 = Agregar_a_tabla_vacias.iloc[:,[0,3]].drop_duplicates().sort_values(by=['PUNTO', 'MES'])
Agregar_a_tabla_vacias_filtrada_2016 = Agregar_a_tabla_vacias_filtrada_2016.groupby(["PUNTO"]).size().to_frame().rename(columns = {0: "Vacios_2016"})

Agregar_a_tabla_vacias_2015 = pesajes_2015_semanas_vacias.groupby(["PUNTO", "MES"]).filter(lambda x: x["SEMANA"].count() >= 3)
Agregar_a_tabla_vacias_filtrada_2015 = Agregar_a_tabla_vacias_2015.iloc[:,[0,3]].drop_duplicates().sort_values(by=['PUNTO', 'MES'])
Agregar_a_tabla_vacias_filtrada_2015 = Agregar_a_tabla_vacias_filtrada_2015.groupby(["PUNTO"]).size().to_frame().rename(columns = {0: "Vacios_2015"})

Tabla_de_Vacios_Completa = pd.merge(Tabla_de_Vacios_Completa, Agregar_a_tabla_vacias_filtrada_2016, how='left', left_index=True, right_index=True).fillna(0)
Tabla_de_Vacios_Completa = pd.merge(Tabla_de_Vacios_Completa, Agregar_a_tabla_vacias_filtrada_2015, how='left', left_index=True, right_index=True).fillna(0)
Tabla_de_Vacios_Completa['Meses_No_Utilizables'] = Tabla_de_Vacios_Completa.Faltantes_2016 + Tabla_de_Vacios_Completa.Vacios_2016 + Tabla_de_Vacios_Completa.Vacios_2015

# Muestro la tabla ordenada por Meses No utilizables
Tabla_de_Vacios_Completa.sort_values(by=['Meses_No_Utilizables'],ascending=False)

,Faltantes_2016,Vacios_2016,Vacios_2015,Meses_No_Utilizables
PUNTO,,,,
PLAZA 25 DE AGOSTO,4,8.0,11.0,23.0
ESTACION VILLA SOLDATI,4,8.0,4.0,16.0
PLAZA VELAZCO IBARRA,3,0.0,4.0,7.0
PLAZA M BELGRANO,3,2.0,0.0,5.0
PLAZA SAN MARTIN,3,1.0,0.0,4.0
PLAZA VERA PENIALOZA,3,0.0,0.0,3.0
PLAZA VELEZ SARSFIELD,3,0.0,0.0,3.0
PLAZA SUDAMERICANA,3,0.0,0.0,3.0
PLAZA SANTOJANNI,3,0.0,0.0,3.0
PLAZA PUEYRREDON,3,0.0,0.0,3.0
PLAZA PALERMO VIEJO,3,0.0,0.0,3.0
PLAZA M DE ANDREA,3,0.0,0.0,3.0
PLAZA GUEMES,3,0.0,0.0,3.0
PLAZA DON BOSCO,3,0.0,0.0,3.0
PLAZA COLOMBIA,3,0.0,0.0,3.0
PLAZA CASTELLI (COMUNA 13),3,0.0,0.0,3.0
PUERTO MADERO,3,0.0,0.0,3.0
PLAZA BALCARCE,3,0.0,0.0,3.0
PLAZA ARENALES,3,0.0,0.0,3.0
PLAZA ALMAGRO,3,0.0,0.0,3.0
PLAZA ALEM,3,0.0,0.0,3.0
PLAZA A DEL VALLE,3,0.0,0.0,3.0
PLAZA 1RO DE MAYO,3,0.0,0.0,3.0
PARQUE SAAVEDRA,3,0.0,0.0,3.0
PARQUE RIVADAVIA,3,0.0,0.0,3.0
PARQUE PATRICIOS,3,0.0,0.0,3.0
PARQUE LOS ANDES,3,0.0,0.0,3.0
PARQUE CHACABUCO,3,0.0,0.0,3.0
PARQUE CENTENARIO,3,0.0,0.0,3.0
PARQUE AVELLANEDA,3,0.0,0.0,3.0
PLAZOLETA REINO DE TAILANDIA,3,0.0,0.0,3.0
PLAZA BOEDO,3,0.0,0.0,3.0

### Decidimos borrar los siguientes 5 de 32 Puntos por tener tantos datos faltantes según el criterio explicado anteriormente
    PLAZA 25 DE AGOSTO
    ESTACION VILLA SOLDATI
    PLAZA VELAZCO IBARRA
    PLAZA M BELGRANO
    PLAZA SAN MARTIN

In [ ]:
pesajes_criterio_de_limpieza = pesajes_con_nan.loc[~pesajes_con_nan['PUNTO'].isin(['ESTACION VILLA SOLDATI',
                                                                 'PLAZA 25 DE AGOSTO',
                                                                 'PLAZA VELAZCO IBARRA',
                                                                 'PLAZA M BELGRANO',
                                                                 'PLAZA SAN MARTIN'])]
pesajes_criterio_de_limpieza.sort_values(by=['PUNTO', 'ANIO', 'MES'])

In [ ]:
pesajes_criterio_de_limpieza.isnull().sum()

Notamos que hay 4 meses que tienen una quinta semana y se encuentra completamente vacia, por lo que decidimos borrar las mismas

In [ ]:
pesajes_1 = pesajes_criterio_de_limpieza.loc[~((pesajes_con_nan['ANIO'] == 2015) & (pesajes_con_nan['MES'] == 6) & (pesajes_con_nan['SEMANA'] == 5))]
pesajes_2 = pesajes_1.loc[~((pesajes_1['ANIO'] == 2015) & (pesajes_1['MES'] == 11) & (pesajes_1['SEMANA'] == 5))]
pesajes_3 = pesajes_2.loc[~((pesajes_2['ANIO'] == 2016) & (pesajes_2['MES'] == 1) & (pesajes_2['SEMANA'] == 5))]
pesajes_sin_quinta_vacias = pesajes_3.loc[~((pesajes_3['ANIO'] == 2016) & (pesajes_3['MES'] == 9) & (pesajes_3['SEMANA'] == 5))]
pesajes_sin_quinta_vacias

In [ ]:
pesajes_sin_quinta_vacias.isnull().sum()

Salvo Plaza Arenales y Parque Centenario, los 25 puntos verdes restantes no tienen datos de octubre, noviembre y diciembre 2016, por lo que los vamos a sacar de nuestro analisis, analizando los 27 puntos verdes desde enero 2015 a septiembre 2016.

In [ ]:
pesajes_sin12 = pesajes_sin_quinta_vacias.loc[~((pesajes_sin_quinta_vacias['ANIO'] == 2016) & (pesajes_sin_quinta_vacias['MES'] == 12))]
pesajes_sin11 = pesajes_sin12.loc[~((pesajes_sin12['ANIO'] == 2016) & (pesajes_sin12['MES'] == 11))]
pesajes_sin_10_11_12 = pesajes_sin11.loc[~((pesajes_sin11['ANIO'] == 2016) & (pesajes_sin11['MES'] == 10))]

In [ ]:
pesajes_sin_10_11_12.isnull().sum()

In [ ]:
export_csv = pesajes_sin_quinta_vacias.to_csv (r' pesajes_nulos.csv', 
                                      index = None, header=True, sep=';')